{ 3,    TD,     sys_read,                   NULL,	"read"                           },  /* 0 */
{ 3,    TD,     sys_write,                  NULL,	"write"                          },  /* 1 */
{ 3,    TD|TF,  sys_open,                   sbox_open,          "open"               },  /* 2 */
{ 1,    TD,     sys_close,                  NULL,	"close"                          },  /* 3 */
{ 2,    TF,     sys_stat,                   sbox_stat,          "stat"               },  /* 4 */
{ 2,    TD,     sys_fstat,                  NULL,	"fstat"                          },  /* 5 */
{ 2,    TF,     sys_lstat,                  sbox_stat,          "lstat"              },  /* 6 */
{ 3,    TD,     sys_poll,                   NULL,	"poll"                           },  /* 7 */
{ 3,    TD,     sys_lseek,                  NULL,	"lseek"                          },  /* 8 */
{ 6,    TD,     sys_mmap,                   sbox_mmap,          "mmap"               },  /* 9 */
{ 3,    0,      sys_mprotect,               sbox_mprotect,      "mprotect"           },  /* 10 */
{ 2,    0,      sys_munmap,                 NULL,	"munmap"                         },  /* 11 */
{ 1,    0,      sys_brk,                    sbox_brk,           "brk"                },  /* 12 */
{ 4,    TS,     sys_rt_sigaction,           NULL,	"rt_sigaction"                   },  /* 13 */
{ 4,    TS,     sys_rt_sigprocmask,         NULL,	"rt_sigprocmask"                 },  /* 14 */
{ 0,    TS,     sys_rt_sigreturn,           NULL,	"rt_sigreturn"                   },  /* 15 */
{ 3,    TD,     sys_ioctl,                  NULL,	"ioctl"                          },  /* 16 */
{ 5,    TD,     sys_pread,                  NULL,	"pread"                          },  /* 17 */
{ 5,    TD,     sys_pwrite,                 NULL,	"pwrite"                         },  /* 18 */
{ 3,    TD,     sys_readv,                  NULL,	"readv"                          },  /* 19 */
{ 3,    TD,     sys_writev,                 NULL,	"writev"                         },  /* 20 */
{ 2,    TF,     sys_access,                 sbox_access,        "access"             },  /* 21 */
{ 1,    TD,     sys_pipe,                   NULL,	"pipe"                           },  /* 22 */
{ 5,    TD,     sys_select,                 NULL,	"select"                         },  /* 23 */
{ 0,    0,      sys_sched_yield,            NULL,	"sched_yield"                    },  /* 24 */
{ 5,    0,      sys_mremap,                 sbox_mremap,        "mremap"             },  /* 25 */
{ 3,    0,      sys_msync,                  NULL,	"msync"                          },  /* 26 */
{ 3,    0,      sys_mincore,                NULL,	"mincore"                        },  /* 27 */
{ 3,    0,      sys_madvise,                NULL,	"madvise"                        },  /* 28 */
{ 4,    TI,     sys_shmget,                 NULL,	"shmget"                         },  /* 29 */
{ 4,    TI,     sys_shmat,                  NULL,	"shmat"                          },  /* 30 */
{ 4,    TI,     sys_shmctl,                 NULL,	"shmctl"                         },  /* 31 */
{ 1,    TD,     sys_dup,                    NULL,	"dup"                            },  /* 32 */
{ 2,    TD,     sys_dup2,                   NULL,	"dup2"                           },  /* 33 */
{ 0,    TS,     sys_pause,                  NULL,	"pause"                          },  /* 34 */
{ 2,    0,      sys_nanosleep,              NULL,	"nanosleep"                      },  /* 35 */
{ 2,    0,      sys_getitimer,              NULL,	"getitimer"                      },  /* 36 */
{ 1,    0,      sys_alarm,                  NULL,	"alarm"                          },  /* 37 */
{ 3,    0,      sys_setitimer,              NULL,	"setitimer"                      },  /* 38 */
{ 0,    0,      sys_getpid,                 NULL,	"getpid"                         },  /* 39 */
{ 4,    TD|TN,  sys_sendfile,               NULL,	"sendfile"                       },  /* 40 */
{ 3,    TN,     sys_socket,                 sbox_socket,        "socket"             },  /* 41 */
{ 3,    TN,     sys_connect,                sbox_connect,       "connect"            },  /* 42 */
{ 3,    TN,     sys_accept,                 NULL,	"accept"                         },  /* 43 */
{ 6,    TN,     sys_sendto,                 NULL,	"sendto"                         },  /* 44 */
{ 6,    TN,     sys_recvfrom,               NULL,	"recvfrom"                       },  /* 45 */
{ 3,    TN,     sys_sendmsg,                NULL,	"sendmsg"                        },  /* 46 */
{ 5,    TN,     sys_recvmsg,                NULL,	"recvmsg"                        },  /* 47 */
{ 2,    TN,     sys_shutdown,               NULL,	"shutdown"                       },  /* 48 */
{ 3,    TN,     sys_bind,                   sbox_bind,          "bind"               },  /* 49 */
{ 2,    TN,     sys_listen,                 NULL,	"listen"                         },  /* 50 */
{ 3,    TN,     sys_getsockname,            NULL,	"getsockname"                    },  /* 51 */
{ 3,    TN,     sys_getpeername,            NULL,	"getpeername"                    },  /* 52 */
{ 4,    TN,     sys_socketpair,             NULL,	"socketpair"                     },  /* 53 */
{ 5,    TN,     sys_setsockopt,             NULL,	"setsockopt"                     },  /* 54 */
{ 5,    TN,     sys_getsockopt,             NULL,	"getsockopt"                     },  /* 55 */
{ 5,    TP,     sys_clone,                  NULL,	"clone"                          },  /* 56 */
{ 0,    TP,     sys_fork,                   NULL,	"fork"                           },  /* 57 */
{ 0,    TP,     sys_vfork,                  NULL,	"vfork"                          },  /* 58 */
{ 3,    TF|TP,  sys_execve,                 sbox_execve,        "execve"             },  /* 59 */
{ 1,    TP,     sys_exit,                   NULL,	"_exit"                          },  /* 60 */
{ 4,    TP,     sys_wait4,                  NULL,	"wait4"                          },  /* 61 */
{ 2,    TS,     sys_kill,                   NULL,	"kill"                           },  /* 62 */
{ 1,    0,      sys_uname,                  NULL,	"uname"                          },  /* 63 */
{ 4,    TI,     sys_semget,                 NULL,	"semget"                         },  /* 64 */
{ 4,    TI,     sys_semop,                  NULL,	"semop"                          },  /* 65 */
{ 4,    TI,     sys_semctl,                 NULL,	"semctl"                         },  /* 66 */
{ 4,    TI,     sys_shmdt,                  NULL,	"shmdt"                          },  /* 67 */
{ 4,    TI,     sys_msgget,                 NULL,	"msgget"                         },  /* 68 */
{ 4,    TI,     sys_msgsnd,                 NULL,	"msgsnd"                         },  /* 69 */
{ 5,    TI,     sys_msgrcv,                 NULL,	"msgrcv"                         },  /* 70 */
{ 3,    TI,     sys_msgctl,                 NULL,   "msgctl"                         },  /* 71 */
{ 3,    TD,     sys_fcntl,                  NULL,   "fcntl"                          },  /* 72 */
{ 2,    TD,     sys_flock,                  NULL,   "flock"                          },  /* 73 */
{ 1,    TD,     sys_fsync,                  NULL,   "fsync"                          },  /* 74 */
{ 1,    TD,     sys_fdatasync,              NULL,   "fdatasync"                      },  /* 75 */
{ 2,    TF,     sys_truncate,               sbox_truncate,      "truncate"           },  /* 76 */
{ 2,    TD,     sys_ftruncate,              NULL,   "ftruncate"                      },  /* 77 */
{ 3,    TD,     sys_getdents,               sbox_getdents,      "getdents"           },  /* 78 */
{ 2,    TF,     sys_getcwd,                 sbox_getcwd,        "getcwd"             },  /* 79 */
{ 1,    TF,     sys_chdir,                  sbox_chdir,         "chdir"              },  /* 80 */
{ 1,    TD,     sys_fchdir,                 NULL,   "fchdir"                         },  /* 81 */
{ 2,    TF,     sys_rename,                 sbox_rename,        "rename"             },  /* 82 */
{ 2,    TF,     sys_mkdir,                  sbox_mkdir,         "mkdir"              },  /* 83 */
{ 1,    TF,     sys_rmdir,                  sbox_rmdir,         "rmdir"              },  /* 84 */
{ 2,    TD|TF,  sys_creat,                  sbox_creat,         "creat"              },  /* 85 */
{ 2,    TF,     sys_link,                   sbox_link,          "link"               },  /* 86 */
{ 1,    TF,     sys_unlink,                 sbox_unlink,        "unlink"             },  /* 87 */
{ 2,    TF,     sys_symlink,                sbox_symlink,       "symlink"            },  /* 88 */
{ 3,    TF,     sys_readlink,               sbox_readlink,      "readlink"           },  /* 89 */
{ 2,    TF,     sys_chmod,                  sbox_chmod,         "chmod"              },  /* 90 */
{ 2,    TD,     sys_fchmod,                 NULL,   "fchmod"                         },  /* 91 */
{ 3,    TF,     sys_chown,                  sbox_chown,         "chown"              },  /* 92 */
{ 3,    TD,     sys_fchown,                 sbox_fchown,        "fchown"             },  /* 93 */
{ 3,    TF,     sys_chown,                  sbox_lchown,        "lchown"             },  /* 94 */
{ 1,    0,      sys_umask,                  NULL,   "umask"                          },  /* 95 */
{ 2,    0,      sys_gettimeofday,           NULL,   "gettimeofday"                   },  /* 96 */
{ 2,    0,      sys_getrlimit,              NULL,   "getrlimit"                      },  /* 97 */
{ 2,    0,      sys_getrusage,              NULL,   "getrusage"                      },  /* 98 */
{ 1,    0,      sys_sysinfo,                NULL,   "sysinfo"                        },  /* 99 */
{ 1,    0,      sys_times,                  NULL,   "times"                          },  /* 100 */
{ 4,    0,      sys_ptrace,                 NULL,   "ptrace"                         },  /* 101 */
{ 0,    NF,     sys_getuid,                 sbox_getroot,       "getuid"             },  /* 102 */
{ 3,    0,      sys_syslog,                 NULL,   "syslog"                         },  /* 103 */
{ 0,    NF,     sys_getgid,                 sbox_getroot,       "getgid"             },  /* 104 */
{ 1,    0,      sys_setuid,                 NULL,   "setuid"                         },  /* 105 */
{ 1,    0,      sys_setgid,                 NULL,   "setgid"                         },  /* 106 */
{ 0,    NF,     sys_geteuid,                sbox_getroot,       "geteuid"            },  /* 107 */
{ 0,    NF,     sys_getegid,                sbox_getroot,       "getegid"            },  /* 108 */
{ 2,    0,      sys_setpgid,                NULL,   "setpgid"                        },  /* 109 */
{ 0,    0,      sys_getppid,                NULL,   "getppid"                        },  /* 110 */
{ 0,    0,      sys_getpgrp,                NULL,   "getpgrp"                        },  /* 111 */
{ 0,    0,      sys_setsid,                 NULL,   "setsid"                         },  /* 112 */
{ 2,    0,      sys_setreuid,               NULL,   "setreuid"                       },  /* 113 */
{ 2,    0,      sys_setregid,               NULL,   "setregid"                       },  /* 114 */
{ 2,    0,      sys_getgroups,              NULL,   "getgroups"                      },  /* 115 */
{ 2,    0,      sys_setgroups,              NULL,   "setgroups"                      },  /* 116 */
{ 3,    0,      sys_setresuid,              NULL,   "setresuid"                      },  /* 117 */
{ 3,    0,      sys_getresuid,              NULL,   "getresuid"                      },  /* 118 */
{ 3,    0,      sys_setresgid,              NULL,   "setresgid"                      },  /* 119 */
{ 3,    0,      sys_getresgid,              NULL,   "getresgid"                      },  /* 120 */
{ 1,    0,      sys_getpgid,                NULL,   "getpgid"                        },  /* 121 */
{ 1,    NF,     sys_setfsuid,               NULL,   "setfsuid"                       },  /* 122 */
{ 1,    NF,     sys_setfsgid,               NULL,   "setfsgid"                       },  /* 123 */
{ 1,    0,      sys_getsid,                 NULL,   "getsid"                         },  /* 124 */
{ 2,    0,      sys_capget,                 NULL,   "capget"                         },  /* 125 */
{ 2,    0,      sys_capset,                 NULL,   "capset"                         },  /* 126 */
{ 2,    TS,     sys_rt_sigpending,          NULL,   "rt_sigpending"                  },  /* 127 */
{ 4,    TS,     sys_rt_sigtimedwait,        NULL,   "rt_sigtimedwait"                },  /* 128 */
{ 3,    TS,     sys_rt_sigqueueinfo,        NULL,   "rt_sigqueueinfo"                },  /* 129 */
{ 2,    TS,     sys_rt_sigsuspend,          NULL,   "rt_sigsuspend"                  },  /* 130 */
{ 2,    TS,     sys_sigaltstack,            NULL,   "sigaltstack"                    },  /* 131 */
{ 2,    TF,     sys_utime,                  sbox_utime,         "utime"              },  /* 132 */
{ 3,    TF,     sys_mknod,                  sbox_mknod,         "mknod"              },  /* 133 */
{ 1,    TF,     sys_uselib,                 sbox_uselib,        "uselib"             },  /* 134 */
{ 1,    0,      sys_personality,            NULL,   "personality"                    },  /* 135 */
{ 2,    0,      sys_ustat,                  NULL,   "ustat"                          },  /* 136 */
{ 2,    TF,     sys_statfs,                 sbox_statfs,        "statfs"             },  /* 137 */
{ 2,    TD,     sys_fstatfs,                NULL,   "fstatfs"                        },  /* 138 */
{ 3,    0,      sys_sysfs,                  NULL,   "sysfs"                          },  /* 139 */
{ 2,    0,      sys_getpriority,            NULL,   "getpriority"                    },  /* 140 */
{ 3,    0,      sys_setpriority,            NULL,   "setpriority"                    },  /* 141 */
{ 0,    0,      sys_sched_setparam,         NULL,   "sched_setparam"                 },  /* 142 */
{ 2,    0,      sys_sched_getparam,         NULL,   "sched_getparam"                 },  /* 143 */
{ 3,    0,      sys_sched_setscheduler,     NULL,   "sched_setscheduler"             },  /* 144 */
{ 1,    0,      sys_sched_getscheduler,     NULL,   "sched_getscheduler"             },  /* 145 */
{ 1,    0,      sys_sched_get_priority_max, NULL,   "sched_get_priority_max"         },  /* 146 */
{ 1,    0,      sys_sched_get_priority_min, NULL,   "sched_get_priority_min"         },  /* 147 */
{ 2,    0,      sys_sched_rr_get_interval,  NULL,   "sched_rr_get_interval"          },  /* 148 */
{ 2,    0,      sys_mlock,                  NULL,   "mlock"                          },  /* 149 */
{ 2,    0,      sys_munlock,                NULL,   "munlock"                        },  /* 150 */
{ 1,    0,      sys_mlockall,               NULL,   "mlockall"                       },  /* 151 */
{ 0,    0,      sys_munlockall,             NULL,   "munlockall"                     },  /* 152 */
{ 0,    0,      sys_vhangup,                NULL,   "vhangup"                        },  /* 153 */
{ 3,    0,      sys_modify_ldt,             NULL,   "modify_ldt"                     },  /* 154 */
{ 2,    TF,     sys_pivotroot,              sbox_not_allowed,   "pivot_root"         },  /* 155 */
{ 1,    0,      sys_sysctl,                 NULL,   "_sysctl"                        },  /* 156 */
{ 5,    0,      sys_prctl,                  sbox_prctl,         "prctl"              },  /* 157 */
{ 2,    TP,     sys_arch_prctl,             NULL,   "arch_prctl"                     },  /* 158 */
{ 1,    0,      sys_adjtimex,               NULL,   "adjtimex"                       },  /* 159 */
{ 2,    0,      sys_setrlimit,              NULL,   "setrlimit"                      },  /* 160 */
{ 1,    TF,     sys_chroot,                 sbox_not_allowed,   "chroot"             },  /* 161 */
{ 0,    0,      sys_sync,                   NULL,   "sync"                           },  /* 162 */
{ 1,    TF,     sys_acct,                   sbox_acct,          "acct"               },  /* 163 */
{ 2,    0,      sys_settimeofday,           NULL,   "settimeofday"                   },  /* 164 */
{ 5,    TF,     sys_mount,                  sbox_not_allowed,   "mount"              },  /* 165 */
{ 2,    TF,     sys_umount2,                sbox_not_allowed,   "umount"             },  /* 166 */
{ 2,    TF,     sys_swapon,                 sbox_not_allowed,   "swapon"             },  /* 167 */
{ 1,    TF,     sys_swapoff,                sbox_not_allowed,   "swapoff"            },  /* 168 */
{ 4,    0,      sys_reboot,                 NULL,   "reboot"                         },  /* 169 */
{ 2,    0,      sys_sethostname,            NULL,   "sethostname"                    },  /* 170 */
{ 2,    0,      sys_setdomainname,          NULL,   "setdomainname"                  },  /* 171 */
{ 1,    0,      sys_iopl,                   NULL,   "iopl"                           },  /* 172 */
{ 3,    0,      sys_ioperm,                 NULL,   "ioperm"                         },  /* 173 */
{ 2,    0,      sys_create_module,          NULL,   "create_module"                  },  /* 174 */
{ 3,    0,      sys_init_module,            NULL,   "init_module"                    },  /* 175 */
{ 2,    0,      sys_delete_module,          NULL,   "delete_module"                  },  /* 176 */
{ 1,    0,      sys_get_kernel_syms,        NULL,   "get_kernel_syms"                },  /* 177 */
{ 5,    0,      sys_query_module,           NULL,   "query_module"                   },  /* 178 */
{ 4,    0,      sys_quotactl,               NULL,   "quotactl"                       },  /* 179 */
{ 3,    0,      sys_nfsservctl,             NULL,   "nfsservctl"                     },  /* 180 */
{ 5,    0,      sys_getpmsg,                NULL,   "getpmsg"                        },  /* 181 */
{ 5,    0,      sys_putpmsg,                NULL,   "putpmsg"                        },  /* 182 */
{ 5,    0,      sys_afs_syscall,            NULL,   "afs_syscall"                    },  /* 183 */
{ 3,    0,      sys_tuxcall,                NULL,   "tuxcall"                        },  /* 184 */
{ 3,    0,      sys_security,               NULL,   "security"                       },  /* 185 */
{ 0,    0,      sys_gettid,                 NULL,   "gettid"                         },  /* 186 */
{ 4,    TD,     sys_readahead,              NULL,   "readahead"                      },  /* 187 */
{ 5,    TF,     sys_setxattr,               sbox_setxattr,      "setxattr"           },  /* 188 */
{ 5,    TF,     sys_setxattr,               sbox_lsetxattr,     "lsetxattr"          },  /* 189 */
{ 5,    TD,     sys_fsetxattr,              NULL,   "fsetxattr"                      },  /* 190 */
{ 4,    TF,     sys_getxattr,               sbox_getxattr,      "getxattr"           },  /* 191 */
{ 4,    TF,     sys_getxattr,               sbox_lgetxattr,     "lgetxattr"          },  /* 192 */
{ 4,    TD,     sys_fgetxattr,              NULL,   "fgetxattr"                      },  /* 193 */
{ 3,    TF,     sys_listxattr,              sbox_listxattr,    "listxattr"           },  /* 194 */
{ 3,    TF,     sys_listxattr,              sbox_llistxattr,   "llistxattr"          },  /* 195 */
{ 3,    TD,     sys_flistxattr,             NULL,   "flistxattr"                     },  /* 196 */
{ 2,    TF,     sys_removexattr,            sbox_removexattr,   "removexattr"        },  /* 197 */
{ 2,    TF,     sys_removexattr,            sbox_lremovexattr,  "lremovexattr"       },  /* 198 */
{ 2,    TD,     sys_fremovexattr,           NULL,   "fremovexattr"                   },  /* 199 */
{ 2,    TS,     sys_kill,                   NULL,   "tkill"                          },  /* 200 */
{ 1,    0,      sys_time,                   NULL,   "time"                           },  /* 201 */
{ 6,    0,      sys_futex,                  NULL,   "futex"                          },  /* 202 */
{ 3,    0,      sys_sched_setaffinity,      NULL,   "sched_setaffinity"              },  /* 203 */
{ 3,    0,      sys_sched_getaffinity,      NULL,   "sched_getaffinity"              },  /* 204 */
{ 1,    0,      sys_set_thread_area,        NULL,   "set_thread_area"                },  /* 205 */
{ 2,    0,      sys_io_setup,               NULL,   "io_setup"                       },  /* 206 */
{ 1,    0,      sys_io_destroy,             NULL,   "io_destroy"                     },  /* 207 */
{ 5,    0,      sys_io_getevents,           NULL,   "io_getevents"                   },  /* 208 */
{ 3,    0,      sys_io_submit,              NULL,   "io_submit"                      },  /* 209 */
{ 3,    0,      sys_io_cancel,              NULL,   "io_cancel"                      },  /* 210 */
{ 1,    0,      sys_get_thread_area,        NULL,   "get_thread_area"                },  /* 211 */
{ 4,    0,      sys_lookup_dcookie,         NULL,   "lookup_dcookie"                 },  /* 212 */
{ 1,    TD,     sys_epoll_create,           NULL,   "epoll_create"                   },  /* 213 */
{ 4,    0,      printargs,                  NULL,   "epoll_ctl_old"                  },  /* 214 */
{ 4,    0,      printargs,                  NULL,   "epoll_wait_old"                 },  /* 215 */
{ 5,    0,      sys_remap_file_pages,       NULL,   "remap_file_pages"               },  /* 216 */
{ 3,    TD,     sys_getdents64,             NULL,   "getdents64"                     },  /* 217 */
{ 1,    0,      sys_set_tid_address,        NULL,   "set_tid_address"                },  /* 218 */
{ 0,    0,      sys_restart_syscall,        NULL,   "restart_syscall"                },  /* 219 */
{ 5,    TI,     sys_semtimedop,             NULL,   "semtimedop"                     },  /* 220 */
{ 4,    TD,     sys_fadvise64_64,           NULL,   "fadvise64"                      },  /* 221 */
{ 3,    0,      sys_timer_create,           NULL,   "timer_create"                   },  /* 222 */
{ 4,    0,      sys_timer_settime,          NULL,   "timer_settime"                  },  /* 223 */
{ 2,    0,      sys_timer_gettime,          NULL,   "timer_gettime"                  },  /* 224 */
{ 1,    0,      sys_timer_getoverrun,       NULL,   "timer_getoverrun"               },  /* 225 */
{ 1,    0,      sys_timer_delete,           NULL,   "timer_delete"                   },  /* 226 */
{ 2,    0,      sys_clock_settime,          NULL,   "clock_settime"                  },  /* 227 */
{ 2,    0,      sys_clock_gettime,          NULL,   "clock_gettime"                  },  /* 228 */
{ 2,    0,      sys_clock_getres,           NULL,   "clock_getres"                   },  /* 229 */
{ 4,    0,      sys_clock_nanosleep,        NULL,   "clock_nanosleep"                },  /* 230 */
{ 1,    TP,     sys_exit,                   NULL,   "exit_group"                     },  /* 231 */
{ 4,    TD,     sys_epoll_wait,             NULL,   "epoll_wait"                     },  /* 232 */
{ 4,    TD,     sys_epoll_ctl,              NULL,   "epoll_ctl"                      },  /* 233 */
{ 3,    TS,     sys_tgkill,                 NULL,   "tgkill"                         },  /* 234 */
{ 2,    TF,     sys_utimes,                 sbox_utimes,        "utimes"             },  /* 235 */
{ 5,    0,      sys_vserver,                NULL,   "vserver"                        },  /* 236 */
{ 6,    0,      sys_mbind,                  NULL,   "mbind"                          },  /* 237 */
{ 3,    0,      sys_set_mempolicy,          NULL,   "set_mempolicy"                  },  /* 238 */
{ 5,    0,      sys_get_mempolicy,          NULL,   "get_mempolicy"                  },  /* 239 */
{ 4,    0,      sys_mq_open,                NULL,   "mq_open"                        },  /* 240 */
{ 1,    0,      sys_mq_unlink,              NULL,   "mq_unlink"                      },  /* 241 */
{ 5,    0,      sys_mq_timedsend,           NULL,   "mq_timedsend"                   },  /* 242 */
{ 5,    0,      sys_mq_timedreceive,        NULL,   "mq_timedreceive"                },  /* 243 */
{ 2,    0,      sys_mq_notify,              NULL,   "mq_notify"                      },  /* 244 */
{ 3,    0,      sys_mq_getsetattr,          NULL,   "mq_getsetattr"                  },  /* 245 */
{ 4,    0,      sys_kexec_load,             NULL,   "kexec_load"                     },  /* 246 */
{ 5,    TP,     sys_waitid,                 NULL,   "waitid"                         },  /* 247 */
{ 5,    0,      sys_add_key,                NULL,   "add_key"                        },  /* 248 */
{ 4,    0,      sys_request_key,            NULL,   "request_key"                    },  /* 249 */
{ 5,    0,      sys_keyctl,                 NULL,   "keyctl"                         },  /* 250 */
{ 3,    0,      sys_ioprio_set,             NULL,   "ioprio_set"                     },  /* 251 */
{ 2,    0,      sys_ioprio_get,             NULL,   "ioprio_get"                     },  /* 252 */
{ 0,    TD,     sys_inotify_init,           NULL,   "inotify_init"                   },  /* 253 */
{ 3,    TD,     sys_inotify_add_watch,      NULL,   "inotify_add_watch"              },  /* 254 */
{ 2,    TD,     sys_inotify_rm_watch,       NULL,   "inotify_rm_watch"               },  /* 255 */
{ 4,    0,      sys_migrate_pages,          NULL,   "migrate_pages"                  },  /* 256 */
{ 4,    TD|TF,  sys_openat,                 sbox_openat,        "openat"             },  /* 257 */
{ 3,    TD|TF,  sys_mkdirat,                sbox_mkdirat,       "mkdirat"            },  /* 258 */
{ 4,    TD|TF,  sys_mknodat,                sbox_mknodat,       "mknodat"            },  /* 259 */
{ 5,    TD|TF,  sys_fchownat,               sbox_fchownat,      "fchownat"           },  /* 260 */
{ 3,    TD|TF,  sys_futimesat,              sbox_futimesat,     "futimesat"          },  /* 261 */
{ 4,    TD|TF,  sys_newfstatat,             sbox_newfstatat,    "newfstatat"         },  /* 262 */
{ 3,    TD|TF,  sys_unlinkat,               sbox_unlinkat,      "unlinkat"           },  /* 263 */
{ 4,    TD|TF,  sys_renameat,               sbox_renameat,      "renameat"           },  /* 264 */
{ 5,    TD|TF,  sys_linkat,                 sbox_linkat,        "linkat"             },  /* 265 */
{ 3,    TD|TF,  sys_symlinkat,              sbox_symlinkat,     "symlinkat"          },  /* 266 */
{ 4,    TD|TF,  sys_readlinkat,             sbox_readlinkat,    "readlinkat"         },  /* 267 */
{ 3,    TD|TF,  sys_fchmodat,               sbox_fchmodat,      "fchmodat"           },  /* 268 */
{ 3,    TD|TF,  sys_faccessat,              sbox_faccessat,     "faccessat"          },  /* 269 */
{ 6,    TD,     sys_pselect6,               NULL,   "pselect6"                       },  /* 270 */
{ 5,    TD,     sys_ppoll,                  NULL,   "ppoll"                          },  /* 271 */
{ 1,    TP,     sys_unshare,                NULL,   "unshare"                        },  /* 272 */
{ 2,    0,      sys_set_robust_list,        NULL,   "set_robust_list"                },  /* 273 */
{ 3,    0,      sys_get_robust_list,        NULL,   "get_robust_list"                },  /* 274 */
{ 6,    TD,     sys_splice,                 NULL,   "splice"                         },  /* 275 */
{ 4,    TD,     sys_tee,                    NULL,   "tee"                            },  /* 276 */
{ 4,    TD,     sys_sync_file_range,        NULL,   "sync_file_range"                },  /* 277 */
{ 4,    TD,     sys_vmsplice,               NULL,   "vmsplice"                       },  /* 278 */
{ 6,    0,      sys_move_pages,             NULL,   "move_pages"                     },  /* 279 */
{ 4,    TD|TF,  sys_utimensat,              sbox_utimensat,     "utimensat"          },  /* 280 */
{ 6,    TD,     sys_epoll_pwait,            NULL,   "epoll_pwait"                    },  /* 281 */
{ 3,    TD|TS,  sys_signalfd,               NULL,   "signalfd"                       },  /* 282 */
{ 2,    TD,     sys_timerfd_create,         NULL,   "timerfd_create"                 },  /* 283 */
{ 1,    TD,     sys_eventfd,                NULL,   "eventfd"                        },  /* 284 */
{ 6,    TD,     sys_fallocate,              NULL,   "fallocate"                      },  /* 285 */
{ 4,    TD,     sys_timerfd_settime,        NULL,   "timerfd_settime"                },  /* 286 */
{ 2,    TD,     sys_timerfd_gettime,        NULL,   "timerfd_gettime"                },  /* 287 */
{ 4,    TN,     sys_accept4,                NULL,   "accept4"                        },  /* 288 */
{ 4,    TD|TS,  sys_signalfd4,              NULL,   "signalfd4"                      },  /* 289 */
{ 2,    TD,     sys_eventfd2,               NULL,   "eventfd2"                       },  /* 290 */
{ 1,    TD,     sys_epoll_create1,          NULL,   "epoll_create1"                  },  /* 291 */
{ 3,    TD,     sys_dup3,                   NULL,   "dup3"                           },  /* 292 */
{ 2,    TD,     sys_pipe2,                  NULL,   "pipe2"                          },  /* 293 */
{ 1,    TD,     sys_inotify_init1,          NULL,   "inotify_init1"                  },  /* 294 */
{ 5,    TD,     sys_preadv,                 NULL,   "preadv"                         },  /* 295 */
{ 5,    TD,     sys_pwritev,                NULL,   "pwritev"                        },  /* 296 */
{ 4,    TP|TS,  sys_rt_tgsigqueueinfo,      NULL,   "rt_tgsigqueueinfo"              },  /* 297 */
{ 5,    TD,     sys_perf_event_open,        NULL,   "perf_event_open"                },  /* 298 */
{ 5,    TN,     sys_recvmmsg,               NULL,   "recvmmsg"                       },  /* 299 */
{ 2,    TD,     sys_fanotify_init,          NULL,   "fanotify_init"                  },  /* 300 */
{ 5,    TD|TF,  sys_fanotify_mark,          sbox_not_allowed,   "fanotify_mark"      },  /* 301 */
{ 4,    0,      sys_prlimit64,              NULL,   "prlimit64"                      },  /* 302 */
{ 5,    TD|TF,  sys_name_to_handle_at,      sbox_not_allowed,   "name_to_handle_at"  },  /* 303 */
{ 3,    TD,     sys_open_by_handle_at,      NULL,   "open_by_handle_at"              },  /* 304 */
{ 2,    0,      sys_clock_adjtime,          NULL,   "clock_adjtime"                  },  /* 305 */
{ 1,    TD,     sys_syncfs,                 NULL,   "syncfs"                         },  /* 306 */
{ 4,    TN,     sys_sendmmsg,               NULL,   "sendmmsg"                       },  /* 307 */
{ 2,    TD,     sys_setns,                  NULL,   "setns"                          },  /* 308 */
{ 3,    0,      sys_getcpu,                 NULL,   "getcpu"                         },  /* 309 */
{ 6,    0,      sys_process_vm_readv,       NULL,   "process_vm_readv"               },  /* 310 */
{ 6,    0,      sys_process_vm_writev,      NULL,   "process_vm_writev"              },  /* 311 */
